/**
 * ROOT LAYOUT — required in every App Router project.
 *
 * It wraps EVERY page of the app and is the only place where <html> and
 * <body> are rendered. Anything you put here (a header, a footer, fonts,
 * global CSS) appears on all pages.
 *
 * Like any layout, it stays mounted while the user navigates between pages;
 * only `children` changes.
 */

// `import type` imports only TypeScript types — it disappears from the
// compiled JavaScript.
import type { Metadata } from "next";
// next/font downloads the font at BUILD time and serves it from your own
// domain: no request to Google from the user's browser, and no layout shift
// while the font loads.
import { Geist, Geist_Mono } from "next/font/google";
// Global CSS (Tailwind + our tokens). Imported once here, applies everywhere.
import "./globals.css";

// Each font call returns an object; `variable` creates a CSS variable
// (--font-geist-sans) that globals.css maps to Tailwind's `font-sans`.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Exporting a `metadata` object is how you set <title>, <meta name="description">
// and more — Next.js writes them into <head> for you. Any page can export its
// own `metadata` to override these defaults.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// `LayoutProps<"/">` is a global type helper generated by Next.js (no import
// needed). For a layout it gives you a typed `children` prop.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // Adds the font CSS variables to <html> so they are available everywhere.
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* `children` = the layout or page for the current URL. */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
