/**
 * ROOT LAYOUT — the default one generated by create-next-app.
 * See class_01_intro/examples/app/layout.tsx for a line-by-line explanation.
 *
 * Note: this layout is a Server Component that renders `children`, which can
 * be Server OR Client Components. Layouts and pages stay on the server unless
 * you add 'use client'.
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
