/**
 * DATABASE SCHEMA — the single source of truth for our tables.
 *
 * We describe the tables in TypeScript. Drizzle then does three jobs from this file:
 *   1. `npm run db:generate` compares it with the previous state and WRITES a SQL
 *      migration into drizzle/ (CREATE TABLE, ALTER TABLE, ...).
 *   2. `npm run db:migrate` RUNS those SQL files against PostgreSQL.
 *   3. The types at the bottom (`$inferSelect`) give us TypeScript types that always
 *      match the tables, so a column rename shows up as a compile error, not a runtime bug.
 *
 * Mapping to the Gatherly domain:
 *   users ──< events >── venues          events belong to ONE organizer (user) and ONE venue
 *   events >──< categories               an event has MANY categories, a category MANY events
 *                                        (the join table is `event_categories`)
 *
 * Column names: we write camelCase in TypeScript (`startsAt`) and Drizzle stores
 * snake_case in PostgreSQL (`starts_at`). That's the `casing: 'snake_case'` option, which
 * must be set in BOTH drizzle.config.ts (generating SQL) and db/index.ts (running queries).
 */
import { relations } from 'drizzle-orm';
import {
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

// A PostgreSQL ENUM: a column that can only hold one of these values. The database itself
// rejects anything else. Heads-up: the spelling here is 'cancelled' (two l's), while the
// older types/event-status.ts used 'canceled'. The database spelling is the one that counts.
export const eventStatus = pgEnum('event_status', ['draft', 'published', 'cancelled']);

// pgTable('table_name', { columns }) declares one table.
// A column is a builder chain: type -> constraints -> default.
export const users = pgTable('users', {
  // uuid primary key, generated by PostgreSQL itself (gen_random_uuid(), built in since
  // PostgreSQL 13). Random UUIDs are hard to guess, unlike 1, 2, 3, ..., so they are safer in URLs.
  id: uuid().primaryKey().defaultRandom(),
  // `.notNull()` -> the column can't be empty (NULL). Without it, the TS type becomes `string | null`.
  // varchar() without a length has no limit, same as text().
  name: varchar().notNull(),
  // `.unique()` -> PostgreSQL refuses two users with the same email.
  email: text().notNull().unique(),
  handle: text().notNull().unique(),
  // A plain text column with a default for now. Later (auth, class 06) roles get checked properly.
  role: text().notNull().default('attendee'),
  // `withTimezone: true` = PostgreSQL `timestamptz`. It stores an exact moment (UTC) and is the
  // right default for "when did this happen"; Drizzle gives us a JS Date. `defaultNow()` = now().
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
});

export const categories = pgTable('categories', {
  id: uuid().primaryKey().defaultRandom(),
  name: varchar().notNull(),
  slug: text().notNull().unique(),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
});

export const venues = pgTable('venues', {
  id: uuid().primaryKey().defaultRandom(),
  name: varchar().notNull(),
  address: varchar().notNull(),
  city: varchar().notNull(),
  country: varchar().notNull(),
  // integer() = whole numbers only.
  capacity: integer().notNull(),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
});

export const events = pgTable('events', {
  id: uuid().primaryKey().defaultRandom(),
  // URL-friendly unique name, used later in /events/[slug].
  slug: text().notNull().unique(),
  title: varchar().notNull(),
  description: varchar().notNull(),
  // No `.notNull()` -> nullable: the TS type is `string | null`. That's why types/gatherly-event.ts
  // overrides it with a plain `string` (the card always needs an image).
  coverImageUrl: text(),
  startsAt: timestamp({ withTimezone: true }).notNull(),
  endsAt: timestamp({ withTimezone: true }).notNull(),
  // New events start as 'draft' unless we say otherwise.
  status: eventStatus().notNull().default('draft'),
  city: varchar().notNull(),
  // Money as whole cents (4900 = 49.00): integers don't suffer from floating-point rounding.
  minPriceCents: integer().notNull().default(0),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),

  // FOREIGN KEYS — a column that points at a row in another table.
  // `.references(() => venues.id)` makes PostgreSQL enforce it: you can't create an event for a
  // venue that doesn't exist, and (no onDelete rule = "no action") you can't delete a venue that
  // still has events. The arrow function `() =>` is lazy, so table order in this file doesn't matter.
  venueId: uuid()
    .notNull()
    .references(() => venues.id),
  organizerId: uuid()
    .notNull()
    .references(() => users.id),
});

// JOIN TABLE for the many-to-many link between events and categories. One row = one pair.
// Instead of an `id` column it uses a COMPOSITE primary key (eventId + categoryId), which also
// guarantees the same pair can't be stored twice.
export const eventCategories = pgTable(
  'event_categories',
  {
    eventId: uuid()
      .notNull()
      // `cascade`: deleting an event automatically deletes its rows here (no orphans left behind).
      .references(() => events.id, { onDelete: 'cascade' }),
    categoryId: uuid()
      .notNull()
      .references(() => categories.id, { onDelete: 'cascade' }),
  },
  (table) => [primaryKey({ columns: [table.eventId, table.categoryId] })],
);

// RELATIONS — tell Drizzle how tables connect, so we can load related rows in ONE query:
//   db.query.events.findMany({ with: { venue: true, organizer: true } })
// This is only for Drizzle's query API. It does NOT change the database. The real constraints
// are the `.references(...)` calls above. `one()` = this row points to one other row (via the
// foreign key); `many()` = other rows point back to this one.
export const usersRelations = relations(users, ({ many }) => ({
  events: many(events),
}));

export const venuesRelations = relations(venues, ({ many }) => ({
  events: many(events),
}));

export const eventsRelations = relations(events, ({ one, many }) => ({
  venue: one(venues, { fields: [events.venueId], references: [venues.id] }),
  organizer: one(users, { fields: [events.organizerId], references: [users.id] }),
  eventCategories: many(eventCategories),
}));

export const categoriesRelations = relations(categories, ({ many }) => ({
  eventCategories: many(eventCategories),
}));

export const eventCategoriesRelations = relations(eventCategories, ({ one }) => ({
  event: one(events, { fields: [eventCategories.eventId], references: [events.id] }),
  category: one(categories, { fields: [eventCategories.categoryId], references: [categories.id] }),
}));

// TYPES inferred from the tables above. `$inferSelect` = the shape of a row we READ.
// (`$inferInsert` would be the shape we pass when INSERTing; columns with defaults become optional.)
// Change a column above and every place that uses these types updates automatically.

export type User = typeof users.$inferSelect;
export type Category = typeof categories.$inferSelect;
export type Venue = typeof venues.$inferSelect;
export type GatherlyEvent = typeof events.$inferSelect;
