/**
 * ROUTE: /routing/[id]   — a DYNAMIC ROUTE
 *
 * A folder name in square brackets is a "dynamic segment". It matches ANY
 * value in that position of the URL and hands it to the page as a param:
 *
 *   /routing/42        -> params = { id: '42' }
 *   /routing/hello     -> params = { id: 'hello' }
 *
 * Note: `/routing/nested` does NOT land here, because a static folder with the
 * same name (`app/routing/nested/`) always wins over a dynamic one.
 *
 * `PageProps<'/routing/[id]'>` is a GLOBAL type helper generated by Next.js
 * (during `next dev`, `next build` or `next typegen`) — that is why there is
 * no import for it. It knows that this route has an `id` param and types it.
 *
 * ⚠️ Since Next.js 15, `params` is a Promise, so it must be `await`-ed.
 *    That's why the component is `async`. Old tutorials that read
 *    `params.id` directly will not work.
 *
 * Only Server Components can be `async` — you can't do this in a
 * 'use client' component.
 */
export default async function Page({ params }: PageProps<'/routing/[id]'>) {
	// Destructure the dynamic segment. Params are ALWAYS strings — convert them
	// yourself if you need a number, e.g. Number(id).
	const { id } = await params;

	return (
		<div>
			Dynamic page. Param value: <strong>{id}</strong>
		</div>
	);
}
