/**
 * shadcn/ui Button — generated by `npx shadcn@latest add button`.
 *
 * IMPORTANT: shadcn/ui is NOT a package you install and import from
 * node_modules. The CLI COPIES this source file into our project, so it is OUR
 * code now. We can read it, change the styles, add a variant. That's the main
 * idea of shadcn/ui ("open code"). Updating later = running the CLI again,
 * which asks before it overwrites anything.
 *
 * How it's built (the same recipe is used by badge.tsx and card.tsx):
 *   - Base UI (`@base-ui/react`) provides the accessible behaviour: focus,
 *     keyboard, ARIA attributes. We chose it when running `shadcn init`
 *     (style "base-nova" in components.json). The other option is Radix UI.
 *   - Tailwind classes provide the looks.
 *   - `cva` (class-variance-authority) maps props to class names, so
 *     <Button variant="outline" size="icon"> picks the matching classes.
 *   - `cn()` merges the result with any `className` the caller passes.
 */
// "Primitive" = the unstyled, accessible Base UI button we wrap with our styles.
import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "cn"

// cva(baseClasses, { variants, defaultVariants }):
//   1st argument = classes EVERY button gets,
//   `variants`   = extra classes per prop value,
//   `defaultVariants` = what you get when the prop is omitted.
// The colours (bg-primary, text-primary-foreground, ...) are the CSS variables
// in app/globals.css, so changing a theme variable restyles every button.
const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center rounded-lg border border-transparent bg-clip-padding text-sm font-medium whitespace-nowrap transition-all outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/80",
        outline:
          "border-border bg-background hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:border-input dark:bg-input/30 dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-[color-mix(in_oklch,var(--secondary),var(--foreground)_5%)] aria-expanded:bg-secondary aria-expanded:text-secondary-foreground",
        ghost:
          "hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:hover:bg-muted/50",
        destructive:
          "bg-destructive/10 text-destructive hover:bg-destructive/20 focus-visible:border-destructive/40 focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:hover:bg-destructive/30 dark:focus-visible:ring-destructive/40",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default:
          "h-8 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        xs: "h-6 gap-1 rounded-[min(var(--radius-md),10px)] px-2 text-xs in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-7 gap-1 rounded-[min(var(--radius-md),12px)] px-2.5 text-[0.8rem] in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3.5",
        lg: "h-9 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        icon: "size-8",
        "icon-xs":
          "size-6 rounded-[min(var(--radius-md),10px)] in-data-[slot=button-group]:rounded-lg [&_svg:not([class*='size-'])]:size-3",
        "icon-sm":
          "size-7 rounded-[min(var(--radius-md),12px)] in-data-[slot=button-group]:rounded-lg",
        "icon-lg": "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

// The component itself: pick classes from the variants, then render the Base UI
// button. `...props` passes everything else (onClick, disabled, type, ...) through.
// `data-slot` is a marker other components can use to style their children.
function Button({
  className,
  variant = "default",
  size = "default",
  ...props
}: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>) {
  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

// buttonVariants is exported too, so a <Link> can LOOK like a button:
//   <Link className={buttonVariants({ variant: "outline" })} href="/events">
export { Button, buttonVariants }
